version: "3.8"

services:
  flask-app:
    build: ./flask-app
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./flask-app/templates:/usr/share/nginx/html/
      - ./flask-app/static:/usr/share/nginx/html/static/
    ports:
      - "80:80"
    depends_on:
      - flask-app

volumes:
  postgres_data:
